### ISSUE TITLE
Support key-based auth outside of filesystem

### ISSUE THREAD

**Issue by fastjames** [Codenaut/exsftpd#4] opened 2022-04-12 21:47 UTC
I'm building a service where I would like to accept input via SFTP, so it's not quite the traditional setup where users are expected to drop files into a filesystem. Consequently, I'd like to store public keys somewhere other than on the filesystem. I figure out how to implement username/password authentication against a database table, but I'm having a slower time figuring out how to do so if a key is provided. I looked at the `authenticate` option, but that function appears to receive only the username, password, and an options map that contains the source IP.

I see that the underlying erlang library provides `:ssh.is_auth_key` which expects to find the authorized public keys in a specific location on the filesystem. I think I would need to write my own replacement that consulted a different source for those authorized keys, but I'm not sure how to get the user-submitted key passed to that function. Do you know of anyone else who has set up exsftpd in this manner?

**Comment by jalpedersen** [comment] 2022-08-02 13:42
duplicate of #5

**Closed as not planned by jalpedersen** 2022-08-02 13:42 UTC
